// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iweghtnlcyiywiuxhfyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3ZWdodG5sY3lpeXdpdXhoZnlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MDY5MDUsImV4cCI6MjA2ODQ4MjkwNX0.wW1yK6g7roMjFfdjdlCbbvUXl7VDZP4nbkmb-uLBmRA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});